name: PR Test
on:
  pull_request:   #pr이벤트를 감지
    branches:
      - test  #test라는 브랜치에 한해서

jobs:
  Run Jest:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: install node
        uses: actions/setup-node@v2
        with :
          node-version: '16'
          cache: 'npm'

      - name: install dependencies
        run: npm i

      - name: Run Test
        run: npm run test

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: test-results
          path: junit.xml
          fail-on-error: 'false'
          reporter: jest-junit        # Format of test results
          token: ${{ secrets.GITHUB_TOKEN }}
