name: PR Test
on:
  pull_request:
    branches:
      - main

jobs:
  checkout:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: install node
        uses: actions/setup-node@v2
        with :
          node-version: '16'
          cache: 'npm'

      - name: install dependencies
        run: npm i

      - name: Run Test
        run: npm run test:git

      - name: Test Report
        uses: IgnusG/jest-report-action@v{ current version }
        if: always() # Or use "continue-on-error: true" in previous test step
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
